name: Deployment

on:
  push:
    branches:
      - master
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

env:
  KUBECTL_VERSION: '1.25.12'
  # TANZU_CLI_VERSION: 'v1.2.0'
  TANZU_TMC_ENDPOINT: ${{ secrets.TANZU_TMC_ENDPOINT }}
  TANZU_API_TOKEN: ${{ secrets.TANZU_API_TOKEN }}
  TANZU_CLI_CEIP_OPT_IN_PROMPT_ANSWER: 'no'

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    # runs-on: ubuntu-latest
    name: Deploy to Kubernetes
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3      

      - name: Show K8s Tools Versions
        run: |
          kubectl version --client
          kubectl cluster-info
          kubectl get nodes
         
      # - name: Set context
      #   uses: azure/k8s-set-context@v4
      #   with:
      #     method: kubeconfig
      #     kubeconfig: ${{ secrets.KUBE_CONFIG }}
      #     # context: ${{ secrets.KUBE_CONTEXT }}

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v5
        with:
          action: deploy
          namespace: hello-node
          skip-tls-verify: true
          manifests: |
            manifest.yaml
