name: Deployment

on:
  push:
    branches:
      - master
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

env:
  TANZU_CLI_VERSION: 'v1.2.0'
  TANZU_CLI_URL: 'https://github.com/vmware-tanzu/tanzu-cli/releases/download/v1.2.0/tanzu-cli-linux-amd64.tar.gz'
  TANZU_CLI_CEIP_OPT_IN_PROMPT_ANSWER: 'no'
  TANZU_TMC_ENDPOINT: ${{ secrets.TANZU_TMC_ENDPOINT }}
  TANZU_API_TOKEN: ${{ secrets.TANZU_API_TOKEN }}
  KUBECTL_VERSION: '1.25.12'

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    name: Deploy to Kubernetes
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      ## This is puking in the lab with a specific version set
      ## but works fine at home ¯\_(ツ)_/¯
      # - name: Set up kubectl
      #   uses: azure/setup-kubectl@v3
      #   with:
      #     version: '1.25.12'

      - name: Setup Kubernetes Tools inc. Tanzu-CLI
        uses: dewab/action-setup-kube-tools@v0.11.1
        with:
          kubectl: ${{ env.KUBECTL_VERSION }}
          tanzu: ${{ env.TANZU_CLI_VERSION }}
          # kustomize: '5.0.0'
          # helm: '3.11.1'
          # kubeconform: '0.5.0'
          # conftest: '0.39.0'
          # rancher: '2.7.0'
          # tilt: '0.31.2'
          # skaffold: '2.1.0'
          # kube-score: '1.16.1'

      - name: Show K8s Tools Versions
        run: |
          kubectl version --client
          kustomize version
          helm version
          kubeconform -v
          conftest --version
          yq --version
          rancher --version
          tilt version
          skaffold version
          kube-score version
          tanzu version
         
      # - name: Install Tanzu CLI
      #   run: |
      #     /usr/bin/wget --no-verbose https://github.com/vmware-tanzu/tanzu-cli/releases/download/${{ env.TANZU_CLI_VERSION }}/tanzu-cli-linux-amd64.tar.gz
      #     /usr/bin/tar -xvzf tanzu-cli-linux-amd64.tar.gz --strip-components 1 ${{ env.TANZU_CLI_VERSION }}/tanzu-cli-linux_amd64
      #     mv tanzu-cli-linux_amd64 tanzu

      - name: Tanzu CLI setup
        run: |
          echo $PATH
          tanzu config eula accept
          tanzu init
          tanzu plugin install --group vmware-tanzucli/essentials
          tanzu plugin install --group vmware-tmc/default
          tanzu plugin install --group vmware-vsphere/default

      - name: Remove Tanzu context, if exists 
        continue-on-error: true
        run: tanzu context delete tmc --yes

      - name: Tanzu CLI login
        run: tanzu context create --endpoint ${{ env.TANZU_TMC_ENDPOINT }} --type tmc tmc

      - name: Set context
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v5
        with:
          action: deploy
          namespace: hello-node
          skip-tls-verify: true
          manifests: |
            manifest.yaml
