name: Deployment

on:
  push:
    branches:
      - master
      - main

  workflow_dispatch:

jobs:
  deploy:
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, Linux, X64]
    name: Deploy to Kubernetes
    steps:

      # - name: Import Secrets
      #   uses: hashicorp/vault-action@latest
      #   with:
      #     url: ${{ secrets.VAULT_ADDR }}
      #     token: ${{ secrets.VAULT_TOKEN }}
      #     caCertificate: ${{ secrets.VAULT_CA_CERT }}
      #     secrets: |
      #       secret/data/production
      
      # - name: Checkout
      #   uses: actions/checkout@v2

      # - name: Set up kubectl
      #   uses: azure/k8s-set-context@v1
      #   with:
      #     kubeconfig: ${{ secrets.KUBE_CONFIG }}
      #     enableCli: true
 
      - name: Setup Kube Tools
        uses: yokawasa/actions-setup-kube-tools@v0.9.3
        with:
          kubectl: '1.25'
          kustomize: '5.0.0'
          helm: '3.11.1'
        
      - run: |
          kubectl version --client
          kustomize version
          helm version
